apps/htmx/urls.py
from django.urls import path

from .views import (
    HomeView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

app_name="htmx"

urlpatterns = [
    path("",        HomeView.as_view(),   name='home'),
    path("list/",   ListView.as_view(),   name='list'),
    path("detail/", DetailView.as_view(), name='detail'),
    path("create/", CreateView.as_view(), name='create'),
    path("update/", UpdateView.as_view(), name='update'),
    path("detail/", DeleteView.as_view(), name='delete'),
]

projectroot/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('jet/', include('jet.urls', namespace='jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
    path('api-auth/v1/', include("rest_framework.urls", namespace='rest_framework')),
    # path('api-auth/', include('rest_framework.urls')),
    
    path("",         include("apps.core.urls", namespace='core')),
    path("blog/",    include("apps.blog.urls", namespace="blog")),
    path("account/", include("apps.users.urls", namespace='users')),
    path("drf/",     include("apps.drf_docs.urls", namespace='drf')),
    path("signals/", include("apps.signals_django.urls", namespace='signals')),
    path('import_export/', include("apps.django_import_export.urls", namespace='django_export_import')),
    path('import/', include("apps.studentExam.urls", namespace='import')),
    path("try-drf/", include("apps.tryDrf.urls", namespace="try-drf")),
    path("jet-reboot/", include("apps.jetReboot.urls", namespace="jet_reboot")),
    path("htmx/", include("apps.htmx.urls", namespace="htmx")),
    # path('celery/',  include("apps.django_celery.urls", namespace='django-celery')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/htmx/models.py
from django.db import models

# Create your models here.

apps/htmx/views.py
from django.shortcuts import render
from django.views import View
from rest_framework.views import APIView
from rest_framework.response import Response
# Create your views here.




class HomeView(View):
    template_name='htmx/index.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, {'status':'success'})


class ListView(View):
    template_name='htmx/list.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class DetailView(View):
    template_name='htmx/detail.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

class CreateView(View):
    template_name='htmx/create.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class UpdateView(View):
    template_name='htmx/update.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class DeleteView(View):
    template_name='htmx/delete.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

templates/htmx/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% block body %}

        {% endblock body %}
    </body>
    <!-- <script src="https://unpkg.com/htmx.org@1.6.1"></script> -->
    <script src="https://unpkg.com/htmx.org@1.6.1" 
    integrity="sha384-tvG/2mnCFmGQzYC1Oh3qxQ7CkQ9kMzYjWZSNtrRZygHPDDqottzEJsqS4oUVodhW" 
    crossorigin="anonymous"></script>
</html>

templates/htmx/index.html
{% extends "htmx/base.html" %}


{% block body %}


    <a href="{% url 'htmx:home' %}">click me</a>

    <button 
        data-hx-post="/clicked"
        data-hx-trigger="click"
        data-hx-target="#parent-div"
        data-hx-swap="outerHTML"
    >   
        click me
    </button>

    <div hx-put="{% url 'htmx:home' %}">
        Put to messages
    </div>

    <dir hx-post="/mouse_entered" hx-trigger="mouseenter">
        [Here mouse, Mouse!]
    </dir>

    <div hx-post="/mouse_entered", hx-trigger="mouseenter once">
        [here mouse, mouse!]
    </div>

{% endblock body %}